"""Service files and the launchctl/systemctl call sequences.

subprocess.run is replaced throughout: these tests assert what the module
writes and which commands it issues, never what launchd/systemd do. POSIX
only, because the generated files are POSIX paths. The Windows refusal is
tested in test_service_cli.py, which runs everywhere.
"""

from __future__ import annotations

import plistlib
import subprocess
import sys
from pathlib import Path

import pytest

from claude_swap.exceptions import ClaudeSwitchError
from claude_swap.maximize import service
from claude_swap.settings import load_prime_settings

pytestmark = pytest.mark.skipif(
    sys.platform == "win32", reason="launchd/systemd service files are POSIX-only"
)

MAC_PROGRAM = ["/Users/u/.local/bin/cc-swap"]
LINUX_PROGRAM = ["/home/u/.local/bin/cc-swap"]
UID = 501


def _done(returncode: int = 0, stdout: str = "", stderr: str = ""):
    return subprocess.CompletedProcess(args=[], returncode=returncode, stdout=stdout, stderr=stderr)


class FakeRun:
    """subprocess.run stand-in: canned replies keyed "tool subcommand"; a
    list replays in order and then repeats its last item. Every argv is kept."""

    def __init__(self, replies: dict | None = None):
        self.replies = {
            k: list(v) if isinstance(v, list) else [v] for k, v in (replies or {}).items()
        }
        self.calls: list[list[str]] = []

    def __call__(self, argv, **kwargs):
        argv = list(argv)
        self.calls.append(argv)
        sub = argv[2] if argv[0] == "systemctl" else argv[1]
        queue = self.replies.get(f"{argv[0]} {sub}")
        if not queue:
            return _done(0)
        return queue.pop(0) if len(queue) > 1 else queue[0]


@pytest.fixture
def fake_run(monkeypatch):
    def install(replies=None):
        fake = FakeRun(replies)
        monkeypatch.setattr(subprocess, "run", fake)
        return fake

    return install


@pytest.fixture
def on_macos(monkeypatch):
    monkeypatch.setattr(sys, "platform", "darwin")


@pytest.fixture
def on_linux(monkeypatch):
    monkeypatch.setattr(sys, "platform", "linux")
    monkeypatch.delenv("XDG_DATA_HOME", raising=False)


def _executable(path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("#!/bin/sh\n")
    path.chmod(0o755)
    return path


# --- generated files (snapshots) ---------------------------------------------------


def test_plist_snapshot():
    parsed = plistlib.loads(
        service.build_plist(MAC_PROGRAM, claude_path="/opt/homebrew/bin/claude", home=Path("/Users/u"))
    )
    assert parsed == {
        "Label": "com.wonjun-lab.cc-swap",
        "ProgramArguments": ["/Users/u/.local/bin/cc-swap", "auto"],
        "RunAtLoad": True,
        "KeepAlive": {"SuccessfulExit": False},
        "ThrottleInterval": 60,
        "ProcessType": "Standard",
        "EnvironmentVariables": {
            "PATH": "/Users/u/.local/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin",
            "PYTHONUNBUFFERED": "1",
            "CC_SWAP_SERVICE": "1",
        },
        "StandardOutPath": "/Users/u/Library/Logs/cc-swap/auto.log",
        "StandardErrorPath": "/Users/u/Library/Logs/cc-swap/auto.err.log",
    }


EXPECTED_UNIT = """\
# Generated by `cc-swap service install`; re-run it instead of editing this file.
[Unit]
Description=cc-swap auto-switch engine (cc-swap auto)
Documentation=https://github.com/wonjun-lab/cc-swap
# A lease-busy exit (code 4) must keep retrying until the other engine stops.
StartLimitIntervalSec=0

[Service]
Type=simple
ExecStart="/home/u/.local/bin/cc-swap" "auto"
Restart=on-failure
RestartSec=60
Environment="PATH=/home/u/.local/bin:/usr/local/bin:/usr/bin:/bin"
Environment="PYTHONUNBUFFERED=1"
Environment="CC_SWAP_SERVICE=1"

[Install]
WantedBy=default.target
"""


def test_unit_snapshot():
    unit = service.build_unit(
        LINUX_PROGRAM, claude_path="/home/u/.local/bin/claude", home=Path("/home/u")
    )
    assert unit == EXPECTED_UNIT


def test_unit_carries_xdg_data_home_so_the_service_reads_the_same_store():
    unit = service.build_unit(
        LINUX_PROGRAM, claude_path=None, home=Path("/home/u"), xdg_data_home="/data/xdg"
    )
    assert 'Environment="XDG_DATA_HOME=/data/xdg"\n' in unit


def test_unit_quotes_spaces_percent_and_dollar():
    unit = service.build_unit(
        ["/home/u/My Tools/$bin/cc-swap"], claude_path="/opt/50%/claude", home=Path("/home/u")
    )
    assert 'ExecStart="/home/u/My Tools/$$bin/cc-swap" "auto"\n' in unit
    assert "/opt/50%%:" in unit


FORWARDED = {
    "CLAUDE_CONFIG_DIR": "/Users/u/alt claude",
    "CLAUDE_SECURESTORAGE_CONFIG_DIR": "/Users/u/secure",
}


def test_plist_forwards_the_claude_profile_env():
    parsed = plistlib.loads(
        service.build_plist(MAC_PROGRAM, claude_path=None, home=Path("/Users/u"), forward_env=FORWARDED)
    )
    env = parsed["EnvironmentVariables"]
    assert env["CLAUDE_CONFIG_DIR"] == "/Users/u/alt claude"
    assert env["CLAUDE_SECURESTORAGE_CONFIG_DIR"] == "/Users/u/secure"
    assert env["PYTHONUNBUFFERED"] == "1" and env["PATH"]


def test_unit_forwards_the_claude_profile_env_quoted():
    unit = service.build_unit(
        LINUX_PROGRAM,
        claude_path=None,
        home=Path("/home/u"),
        forward_env={
            "CLAUDE_CONFIG_DIR": '/home/u/My "Profiles"/50%/$x',
            "CLAUDE_SECURESTORAGE_CONFIG_DIR": "/home/u/secure",
        },
    )
    # `%` is a specifier in every setting; `$` means nothing in Environment=.
    assert 'Environment="CLAUDE_CONFIG_DIR=/home/u/My \\"Profiles\\"/50%%/$x"\n' in unit
    assert 'Environment="CLAUDE_SECURESTORAGE_CONFIG_DIR=/home/u/secure"\n' in unit


def test_unit_forwards_a_defined_but_empty_securestorage_dir():
    unit = service.build_unit(
        LINUX_PROGRAM, claude_path=None, home=Path("/home/u"),
        forward_env={"CLAUDE_SECURESTORAGE_CONFIG_DIR": ""},
    )
    assert 'Environment="CLAUDE_SECURESTORAGE_CONFIG_DIR="\n' in unit


def test_service_path_puts_the_program_and_claude_first():
    path = service.service_path(
        ["/opt/tools/cc-swap"], "/srv/claude/bin/claude", platform="linux", home=Path("/home/u")
    )
    assert path.split(":")[:3] == ["/opt/tools", "/srv/claude/bin", "/home/u/.local/bin"]


# --- program and claude resolution ----------------------------------------------------


def test_resolve_program_prefers_the_cc_swap_console_script(tmp_path, monkeypatch):
    script = _executable(tmp_path / "cc-swap")
    monkeypatch.setattr(sys, "argv", [str(script)])
    assert service.resolve_program() == [str(script)]


def test_resolve_program_finds_cc_swap_beside_a_cswap_invocation(tmp_path, monkeypatch):
    cswap = _executable(tmp_path / "cswap")
    sibling = _executable(tmp_path / "cc-swap")
    monkeypatch.setattr(sys, "argv", [str(cswap)])
    assert service.resolve_program() == [str(sibling)]


def test_resolve_program_falls_back_to_the_interpreter(tmp_path, monkeypatch):
    monkeypatch.setattr(sys, "argv", [str(tmp_path / "pytest")])
    monkeypatch.setattr(service.shutil, "which", lambda name: None)
    assert service.resolve_program() == [sys.executable, "-m", "claude_swap"]


def test_detect_claude_path_order(tmp_path, monkeypatch):
    configured = _executable(tmp_path / "custom" / "claude")
    on_path = _executable(tmp_path / "brew" / "claude")
    local = _executable(tmp_path / "home" / ".local" / "bin" / "claude")
    monkeypatch.setattr(service.shutil, "which", lambda name: str(on_path))
    home = tmp_path / "home"
    assert service.detect_claude_path(str(configured), home=home) == str(configured)
    assert service.detect_claude_path(str(tmp_path / "gone"), home=home) == str(on_path)
    monkeypatch.setattr(service.shutil, "which", lambda name: None)
    assert service.detect_claude_path(None, home=home) == str(local)
    local.unlink()
    assert service.detect_claude_path(None, home=home) is None


def test_detect_claude_path_keeps_the_versioned_symlink_unresolved(tmp_path, monkeypatch):
    target = _executable(tmp_path / "versions" / "2.1.0")
    link = tmp_path / "home" / ".local" / "bin" / "claude"
    link.parent.mkdir(parents=True)
    link.symlink_to(target)
    monkeypatch.setattr(service.shutil, "which", lambda name: None)
    assert service.detect_claude_path(None, home=tmp_path / "home") == str(link)


# --- install ---------------------------------------------------------------------------


def test_install_macos_writes_bootstraps_and_saves_claude_path(tmp_path, on_macos, fake_run, monkeypatch):
    claude = _executable(tmp_path / "brew" / "claude")
    monkeypatch.setattr(service.shutil, "which", lambda name: str(claude))
    root = tmp_path / "root"
    run = fake_run({"launchctl print": _done(1)})
    result = service.install(home=tmp_path, program=MAC_PROGRAM, uid=UID, backup_root=root)
    plist = Path(result["path"])
    assert plist == tmp_path / "Library" / "LaunchAgents" / "com.wonjun-lab.cc-swap.plist"
    assert plistlib.loads(plist.read_bytes())["ProgramArguments"] == [*MAC_PROGRAM, "auto"]
    assert (tmp_path / "Library" / "Logs" / "cc-swap").is_dir()
    assert ["launchctl", "bootstrap", f"gui/{UID}", str(plist)] in run.calls
    assert "bootout" not in [c[1] for c in run.calls]
    assert result["claude_path"] == str(claude) and result["claude_path_saved"] is True
    assert load_prime_settings(root).claude_path == str(claude)


def test_install_macos_reloads_an_already_loaded_job(tmp_path, on_macos, fake_run, monkeypatch):
    monkeypatch.setattr(service.shutil, "which", lambda name: None)
    run = fake_run({"launchctl print": [_done(0), _done(1)]})
    service.install(home=tmp_path, program=MAC_PROGRAM, uid=UID, backup_root=tmp_path / "root")
    subs = [c[1] for c in run.calls]
    assert subs.index("bootout") < subs.index("bootstrap")


def test_install_macos_raises_with_launchctl_detail(tmp_path, on_macos, fake_run, monkeypatch):
    monkeypatch.setattr(service.shutil, "which", lambda name: None)
    fake_run({"launchctl print": _done(1), "launchctl bootstrap": _done(5, stderr="Input/output error")})
    with pytest.raises(ClaudeSwitchError, match="Input/output error"):
        service.install(home=tmp_path, program=MAC_PROGRAM, uid=UID, backup_root=tmp_path / "root")


def test_install_linux_writes_unit_then_reloads_and_enables(tmp_path, on_linux, fake_run, monkeypatch):
    monkeypatch.setattr(service.shutil, "which", lambda name: None)
    run = fake_run({
        "systemctl is-active": _done(3),
        "loginctl show-user": _done(0, "no\n"),
    })
    result = service.install(home=tmp_path, program=LINUX_PROGRAM, backup_root=tmp_path / "root", user="u")
    unit = tmp_path / ".config" / "systemd" / "user" / "cc-swap.service"
    assert result["path"] == str(unit) and unit.exists()
    assert 'ExecStart="/home/u/.local/bin/cc-swap" "auto"' in unit.read_text()
    assert run.calls == [
        ["systemctl", "--user", "is-active", "--quiet", "cc-swap.service"],
        ["systemctl", "--user", "daemon-reload"],
        ["systemctl", "--user", "enable", "--now", "cc-swap.service"],
        ["loginctl", "show-user", "u", "--property=Linger", "--value"],
    ]
    assert result["linger"] is False
    assert result["logs"] == ["journalctl --user -u cc-swap.service -f"]


def test_install_linux_restarts_a_running_service_onto_the_new_build(tmp_path, on_linux, fake_run, monkeypatch):
    monkeypatch.setattr(service.shutil, "which", lambda name: None)
    run = fake_run({"systemctl is-active": _done(0), "loginctl show-user": _done(0, "yes\n")})
    result = service.install(home=tmp_path, program=LINUX_PROGRAM, backup_root=tmp_path / "root", user="u")
    assert ["systemctl", "--user", "restart", "cc-swap.service"] in run.calls
    assert result["linger"] is True


def test_install_linux_passes_xdg_data_home_into_the_unit(tmp_path, on_linux, fake_run, monkeypatch):
    monkeypatch.setattr(service.shutil, "which", lambda name: None)
    monkeypatch.setenv("XDG_DATA_HOME", str(tmp_path / "xdg"))
    fake_run({"systemctl is-active": _done(3)})
    result = service.install(home=tmp_path, program=LINUX_PROGRAM, backup_root=tmp_path / "root", user="u")
    assert f'Environment="XDG_DATA_HOME={tmp_path / "xdg"}"' in Path(result["path"]).read_text()


def test_install_macos_forwards_the_claude_profile_env_into_the_plist(tmp_path, on_macos, fake_run, monkeypatch):
    monkeypatch.setattr(service.shutil, "which", lambda name: None)
    monkeypatch.setenv("CLAUDE_CONFIG_DIR", str(tmp_path / "alt"))
    monkeypatch.setenv("CLAUDE_SECURESTORAGE_CONFIG_DIR", str(tmp_path / "secure"))
    fake_run({"launchctl print": _done(1)})
    result = service.install(home=tmp_path, program=MAC_PROGRAM, uid=UID, backup_root=tmp_path / "root")
    env = plistlib.loads(Path(result["path"]).read_bytes())["EnvironmentVariables"]
    assert env["CLAUDE_CONFIG_DIR"] == str(tmp_path / "alt")
    assert env["CLAUDE_SECURESTORAGE_CONFIG_DIR"] == str(tmp_path / "secure")
    assert result["forwarded_env"] == {
        "CLAUDE_CONFIG_DIR": str(tmp_path / "alt"),
        "CLAUDE_SECURESTORAGE_CONFIG_DIR": str(tmp_path / "secure"),
    }


def test_install_linux_forwards_the_claude_profile_env_into_the_unit(tmp_path, on_linux, fake_run, monkeypatch):
    monkeypatch.setattr(service.shutil, "which", lambda name: None)
    monkeypatch.setenv("CLAUDE_CONFIG_DIR", str(tmp_path / "alt"))
    fake_run({"systemctl is-active": _done(3)})
    result = service.install(home=tmp_path, program=LINUX_PROGRAM, backup_root=tmp_path / "root", user="u")
    text = Path(result["path"]).read_text()
    assert f'Environment="CLAUDE_CONFIG_DIR={tmp_path / "alt"}"\n' in text
    assert "CLAUDE_SECURESTORAGE_CONFIG_DIR" not in text
    assert result["forwarded_env"] == {"CLAUDE_CONFIG_DIR": str(tmp_path / "alt")}


def test_install_forwards_nothing_when_the_profile_env_is_absent(tmp_path, on_macos, fake_run, monkeypatch):
    monkeypatch.setattr(service.shutil, "which", lambda name: None)
    monkeypatch.setenv("CLAUDE_CONFIG_DIR", "")  # empty means "unset" to claude
    fake_run({"launchctl print": _done(1)})
    result = service.install(home=tmp_path, program=MAC_PROGRAM, uid=UID, backup_root=tmp_path / "root")
    env = plistlib.loads(Path(result["path"]).read_bytes())["EnvironmentVariables"]
    assert set(env) == {"PATH", "PYTHONUNBUFFERED", "CC_SWAP_SERVICE"}
    assert result["forwarded_env"] == {}


def test_install_forwards_a_defined_but_empty_securestorage_dir(tmp_path, on_macos, fake_run, monkeypatch):
    monkeypatch.setattr(service.shutil, "which", lambda name: None)
    monkeypatch.setenv("CLAUDE_SECURESTORAGE_CONFIG_DIR", "")
    fake_run({"launchctl print": _done(1)})
    result = service.install(home=tmp_path, program=MAC_PROGRAM, uid=UID, backup_root=tmp_path / "root")
    env = plistlib.loads(Path(result["path"]).read_bytes())["EnvironmentVariables"]
    assert env["CLAUDE_SECURESTORAGE_CONFIG_DIR"] == ""
    assert result["forwarded_env"] == {"CLAUDE_SECURESTORAGE_CONFIG_DIR": ""}


# --- refresh keeps the installed environment ---------------------------------------


def _seed_installed_plist(home: Path, env: dict) -> Path:
    path = service.plist_path(home)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(
        plistlib.dumps({"ProgramArguments": [*MAC_PROGRAM, "auto"], "EnvironmentVariables": env})
    )
    return path


def test_read_installed_reads_a_plist(tmp_path, on_macos):
    _seed_installed_plist(tmp_path, {"CLAUDE_CONFIG_DIR": "/alt", "CC_SWAP_SERVICE": "1"})
    argv, env = service.read_installed(platform="darwin", home=tmp_path)
    assert argv == MAC_PROGRAM
    assert env == {"CLAUDE_CONFIG_DIR": "/alt", "CC_SWAP_SERVICE": "1"}


def test_read_installed_reads_a_unit(tmp_path, on_linux):
    unit = service.unit_path(tmp_path)
    unit.parent.mkdir(parents=True)
    unit.write_text(
        service.build_unit(
            LINUX_PROGRAM, claude_path=None, home=tmp_path,
            forward_env={"CLAUDE_CONFIG_DIR": "/a b/c"},
        )
    )
    argv, env = service.read_installed(platform="linux", home=tmp_path)
    assert argv == LINUX_PROGRAM
    assert env["CLAUDE_CONFIG_DIR"] == "/a b/c"


def test_read_installed_is_none_without_a_file(tmp_path, on_macos):
    assert service.read_installed(platform="darwin", home=tmp_path) is None


def test_refresh_macos_keeps_the_installed_profile_env_not_the_shells(
    tmp_path, on_macos, fake_run, monkeypatch
):
    monkeypatch.setattr(service.shutil, "which", lambda name: None)
    _seed_installed_plist(tmp_path, {"CLAUDE_CONFIG_DIR": "/installed"})
    monkeypatch.setenv("CLAUDE_CONFIG_DIR", "/shell")
    monkeypatch.setenv("CLAUDE_SECURESTORAGE_CONFIG_DIR", "/shell-secure")
    fake_run({"launchctl print": _done(1)})
    result = service.install(
        home=tmp_path, program=MAC_PROGRAM, uid=UID, backup_root=tmp_path / "root",
        reuse_installed_env=True,
    )
    env = plistlib.loads(Path(result["path"]).read_bytes())["EnvironmentVariables"]
    assert env["CLAUDE_CONFIG_DIR"] == "/installed"
    assert "CLAUDE_SECURESTORAGE_CONFIG_DIR" not in env
    assert result["forwarded_env"] == {"CLAUDE_CONFIG_DIR": "/installed"}
    assert result["env_source"] == "installed"


def test_refresh_macos_installed_without_profile_env_forwards_nothing(
    tmp_path, on_macos, fake_run, monkeypatch
):
    monkeypatch.setattr(service.shutil, "which", lambda name: None)
    _seed_installed_plist(tmp_path, {"CC_SWAP_SERVICE": "1"})
    monkeypatch.setenv("CLAUDE_CONFIG_DIR", "/shell")
    fake_run({"launchctl print": _done(1)})
    result = service.install(
        home=tmp_path, program=MAC_PROGRAM, uid=UID, backup_root=tmp_path / "root",
        reuse_installed_env=True,
    )
    env = plistlib.loads(Path(result["path"]).read_bytes())["EnvironmentVariables"]
    assert "CLAUDE_CONFIG_DIR" not in env
    assert result["forwarded_env"] == {}


def test_refresh_keeps_an_empty_securestorage_dir(tmp_path, on_macos, fake_run, monkeypatch):
    monkeypatch.setattr(service.shutil, "which", lambda name: None)
    _seed_installed_plist(tmp_path, {"CLAUDE_SECURESTORAGE_CONFIG_DIR": ""})
    fake_run({"launchctl print": _done(1)})
    result = service.install(
        home=tmp_path, program=MAC_PROGRAM, uid=UID, backup_root=tmp_path / "root",
        reuse_installed_env=True,
    )
    assert result["forwarded_env"] == {"CLAUDE_SECURESTORAGE_CONFIG_DIR": ""}


def test_refresh_linux_keeps_the_installed_env_and_xdg(tmp_path, on_linux, fake_run, monkeypatch):
    monkeypatch.setattr(service.shutil, "which", lambda name: None)
    unit = service.unit_path(tmp_path)
    unit.parent.mkdir(parents=True)
    unit.write_text(
        service.build_unit(
            LINUX_PROGRAM, claude_path=None, home=tmp_path, xdg_data_home="/data/installed",
            forward_env={"CLAUDE_CONFIG_DIR": "/installed"},
        )
    )
    monkeypatch.setenv("CLAUDE_CONFIG_DIR", "/shell")
    monkeypatch.setenv("XDG_DATA_HOME", "/data/shell")
    fake_run({"systemctl is-active": _done(3)})
    result = service.install(
        home=tmp_path, program=LINUX_PROGRAM, backup_root=tmp_path / "root", user="u",
        reuse_installed_env=True,
    )
    text = unit.read_text()
    assert 'Environment="CLAUDE_CONFIG_DIR=/installed"' in text
    assert "/shell" not in text
    assert 'Environment="XDG_DATA_HOME=/data/installed"' in text
    assert result["forwarded_env"] == {"CLAUDE_CONFIG_DIR": "/installed"}


def test_refresh_without_a_readable_installed_file_refuses_rather_than_use_the_shell(
    tmp_path, on_macos, fake_run, monkeypatch
):
    monkeypatch.setattr(service.shutil, "which", lambda name: None)
    monkeypatch.setenv("CLAUDE_CONFIG_DIR", "/shell")
    run = fake_run({"launchctl print": _done(1)})
    with pytest.raises(ClaudeSwitchError, match="cc-swap service install"):
        service.install(
            home=tmp_path, program=MAC_PROGRAM, uid=UID, backup_root=tmp_path / "root",
            reuse_installed_env=True,
        )
    assert not run.calls


def test_bootstrap_failure_after_a_successful_bootout_says_the_service_is_stopped(
    tmp_path, on_macos, fake_run, monkeypatch
):
    monkeypatch.setattr(service.shutil, "which", lambda name: None)
    fake_run({
        "launchctl print": [_done(0), _done(1)],
        "launchctl bootout": _done(0),
        "launchctl bootstrap": _done(5, stderr="Input/output error"),
    })
    with pytest.raises(ClaudeSwitchError) as excinfo:
        service.install(home=tmp_path, program=MAC_PROGRAM, uid=UID, backup_root=tmp_path / "root")
    message = str(excinfo.value)
    assert "the service is now STOPPED" in message
    assert "run: cc-swap service install" in message
    assert "Input/output error" in message


def test_bootstrap_failure_without_a_bootout_does_not_claim_stopped(
    tmp_path, on_macos, fake_run, monkeypatch
):
    monkeypatch.setattr(service.shutil, "which", lambda name: None)
    fake_run({"launchctl print": _done(1), "launchctl bootstrap": _done(5, stderr="boom")})
    with pytest.raises(ClaudeSwitchError) as excinfo:
        service.install(home=tmp_path, program=MAC_PROGRAM, uid=UID, backup_root=tmp_path / "root")
    assert "STOPPED" not in str(excinfo.value)


def test_reinstall_command_asks_for_the_installed_env(monkeypatch):
    monkeypatch.setattr(service, "resolve_program", lambda: ["/x/cc-swap"])
    assert service.reinstall_command() == [
        "/x/cc-swap", "service", "install", "--reuse-installed-env",
    ]


@pytest.mark.parametrize("platform_fixture", ["on_macos", "on_linux"])
def test_install_refuses_when_claude_config_dir_is_a_cswap_run_session_profile(
    tmp_path, request, fake_run, monkeypatch, platform_fixture
):
    request.getfixturevalue(platform_fixture)
    root = tmp_path / "root"
    profile = root / "sessions" / "2-user_example.com"
    profile.mkdir(parents=True)
    monkeypatch.setattr(service.shutil, "which", lambda name: "/opt/homebrew/bin/claude")
    monkeypatch.setenv("CLAUDE_CONFIG_DIR", str(profile))
    run = fake_run()
    with pytest.raises(ClaudeSwitchError, match="session profile") as excinfo:
        service.install(home=tmp_path, program=MAC_PROGRAM, uid=UID, backup_root=root)
    assert str(profile) in str(excinfo.value)
    assert "unset CLAUDE_CONFIG_DIR" in str(excinfo.value)
    assert run.calls == []  # no launchctl / systemctl
    assert not service.plist_path(tmp_path).exists() and not service.unit_path(tmp_path).exists()
    assert load_prime_settings(root).claude_path is None  # nothing was saved either


def test_install_refuses_a_path_inside_a_session_profile_too(tmp_path, on_linux, fake_run, monkeypatch):
    root = tmp_path / "root"
    monkeypatch.setenv("CLAUDE_CONFIG_DIR", str(root / "sessions" / "7-a_x.com" / "nested"))
    fake_run()
    with pytest.raises(ClaudeSwitchError, match="session profile"):
        service.install(home=tmp_path, program=LINUX_PROGRAM, backup_root=root, user="u")


def test_install_accepts_a_config_dir_beside_the_session_profiles(tmp_path, on_linux, fake_run, monkeypatch):
    monkeypatch.setattr(service.shutil, "which", lambda name: None)
    root = tmp_path / "root"
    monkeypatch.setenv("CLAUDE_CONFIG_DIR", str(root / "sessions" / "scratch"))
    fake_run({"systemctl is-active": _done(3)})
    result = service.install(home=tmp_path, program=LINUX_PROGRAM, backup_root=root, user="u")
    assert result["forwarded_env"] == {"CLAUDE_CONFIG_DIR": str(root / "sessions" / "scratch")}


def test_install_linux_surfaces_a_systemctl_failure(tmp_path, on_linux, fake_run, monkeypatch):
    monkeypatch.setattr(service.shutil, "which", lambda name: None)
    fake_run({
        "systemctl is-active": _done(3),
        "systemctl daemon-reload": _done(1, stderr="Failed to connect to bus"),
    })
    with pytest.raises(ClaudeSwitchError, match="daemon-reload failed.*Failed to connect to bus"):
        service.install(home=tmp_path, program=LINUX_PROGRAM, backup_root=tmp_path / "root", user="u")


def test_install_linux_without_systemctl(tmp_path, on_linux, monkeypatch):
    def missing(argv, **kwargs):
        raise FileNotFoundError(argv[0])

    monkeypatch.setattr(subprocess, "run", missing)
    monkeypatch.setattr(service.shutil, "which", lambda name: None)
    with pytest.raises(ClaudeSwitchError, match="systemctl not found"):
        service.install(home=tmp_path, program=LINUX_PROGRAM, backup_root=tmp_path / "root", user="u")


def test_install_rejects_a_claude_path_that_is_not_executable(tmp_path, on_linux, fake_run):
    fake_run()
    with pytest.raises(ClaudeSwitchError, match="not an executable file"):
        service.install(claude_path=str(tmp_path / "nope"), home=tmp_path,
                        program=LINUX_PROGRAM, backup_root=tmp_path / "root", user="u")


def test_install_keeps_a_valid_configured_claude_path(tmp_path, on_linux, fake_run, monkeypatch):
    from claude_swap.settings import set_setting

    claude = _executable(tmp_path / "custom" / "claude")
    root = tmp_path / "root"
    set_setting(root, "prime.claudePath", str(claude))
    monkeypatch.setattr(service.shutil, "which", lambda name: "/elsewhere/claude")
    fake_run({"systemctl is-active": _done(3)})
    result = service.install(home=tmp_path, program=LINUX_PROGRAM, backup_root=root, user="u")
    assert result["claude_path"] == str(claude)
    assert result["claude_path_saved"] is False


# --- uninstall / status -----------------------------------------------------------


def test_uninstall_linux_disables_then_removes_the_unit(tmp_path, on_linux, fake_run):
    unit = service.unit_path(tmp_path)
    unit.parent.mkdir(parents=True)
    unit.write_text("x")
    run = fake_run({"systemctl is-active": [_done(0), _done(3)]})
    result = service.uninstall(home=tmp_path)
    assert result == {"platform": "linux", "name": "cc-swap.service", "was_running": True, "removed": True}
    assert not unit.exists()
    assert [c[2] for c in run.calls] == ["is-active", "disable", "is-active", "daemon-reload"]


def test_uninstall_linux_refuses_to_orphan_a_running_unit(tmp_path, on_linux, fake_run):
    unit = service.unit_path(tmp_path)
    unit.parent.mkdir(parents=True)
    unit.write_text("x")
    fake_run({"systemctl is-active": _done(0)})
    with pytest.raises(ClaudeSwitchError, match="still running"):
        service.uninstall(home=tmp_path)
    assert unit.exists()


def test_uninstall_macos_boots_out_and_removes_the_plist(tmp_path, on_macos, fake_run):
    plist = service.plist_path(tmp_path)
    plist.parent.mkdir(parents=True)
    plist.write_bytes(b"x")
    run = fake_run({"launchctl print": [_done(0), _done(1)]})
    result = service.uninstall(home=tmp_path, uid=UID)
    assert result == {"platform": "darwin", "name": "com.wonjun-lab.cc-swap", "was_running": True, "removed": True}
    assert ["launchctl", "bootout", f"gui/{UID}/com.wonjun-lab.cc-swap"] in run.calls
    assert not plist.exists()


def test_status_linux_reads_state_and_pid(tmp_path, on_linux, fake_run):
    unit = service.unit_path(tmp_path)
    unit.parent.mkdir(parents=True)
    unit.write_text("x")
    fake_run({"systemctl is-active": _done(0, "active\n"), "systemctl show": _done(0, "4242\n")})
    result = service.status(home=tmp_path)
    assert result["installed"] and result["loaded"] and result["running"]
    assert (result["state"], result["pid"]) == ("active", 4242)


def test_status_linux_not_installed(tmp_path, on_linux, fake_run):
    fake_run({"systemctl is-active": _done(3, "inactive\n"), "systemctl show": _done(0, "0\n")})
    result = service.status(home=tmp_path)
    assert not result["installed"] and not result["loaded"] and not result["running"]
    assert result["pid"] is None


def test_status_macos_reads_launchctl_print(tmp_path, on_macos, fake_run):
    plist = service.plist_path(tmp_path)
    plist.parent.mkdir(parents=True)
    plist.write_bytes(b"x")
    fake_run({"launchctl print": _done(0, "\tstate = running\n\tpid = 99\n")})
    result = service.status(home=tmp_path, uid=UID)
    assert result["installed"] and result["running"]
    assert result["pid"] == 99
    assert result["logs"][0] == str(tmp_path / "Library" / "Logs" / "cc-swap" / "auto.log")


@pytest.mark.parametrize("stdout,expected", [("yes\n", True), ("no\n", False), ("\n", None)])
def test_linger_enabled_parses_loginctl(fake_run, stdout, expected):
    fake_run({"loginctl show-user": _done(0, stdout)})
    assert service.linger_enabled("u") is expected
